Ot126 45
alkemyTech/OT126-SERVER pull request #12
Opened 2022-01-21 21:18 UTC by GimenaRivoira

getById in Slide completed and working successfully

2022-01-25 04:26 UTC, manuelfrancisco requested changes

2022-01-25 04:26 UTC, manuelfrancisco commented on controllers/slides.js
> +const getById = async (req, res, next) => {
Esto pertenece a otra tarea, para la próxima porfa en otro PR

2022-01-25 04:26 UTC, manuelfrancisco commented on controllers/slides.js
> +    if (data) {
Esta validación debería ir en el service y hacer un throw error en vez de escribir en la respuesta

2022-01-25 21:30 UTC, manuelfrancisco requested changes

2022-01-25 21:30 UTC, manuelfrancisco commented on services/slides.js
> +  if (id) {
Esta no es la validación que estaba antes en el controller, sería guardar el resultado del getById en una constante y si eso es null hacer un throw de un error con status 404

2022-01-25 21:44 UTC, GimenaRivoira commented on services/slides.js
> +  if (id) {
Ah perdon, eso te queria preguntar, el manejo de errores devuelve un HTML, y creo que no hablamos de eso en la Reunión. Pero sI yo lo mando asi, me salta el html y no me toma el mensaje ni throw error. lo hago asi de todas formas? o como seria en ese caso?

2022-01-25 22:53 UTC, manuelfrancisco requested changes

2022-01-25 22:53 UTC, manuelfrancisco commented on services/slides.js
> +  if (id) {
Sí, hacelo así de todas formas.

2022-01-25 23:04 UTC, GimenaRivoira commented
Adjunto como quedo con las correcciones. 
![image](https://user-images.githubusercontent.com/73909780/151074484-f95ba204-6de2-40c2-8fe2-44a648632a39.png)

2022-01-26 00:51 UTC, manuelfrancisco approved these changes

2022-01-26 01:04 UTC, merged