Ot126 46
alkemyTech/OT126-SERVER pull request #15
Opened 2022-01-22 00:16 UTC by GimenaRivoira

Validation for Create in Slide working

2022-01-25 04:36 UTC, manuelfrancisco requested changes

2022-01-25 04:36 UTC, manuelfrancisco commented on controllers/slides.js
> +    if (data) {
Lo mismo que en el otro PR, esta validación va en el service

2022-01-25 04:36 UTC, manuelfrancisco commented on controllers/slides.js
> +const getById = async (req, res, next) => {
Lo mismo que en el otro PR, para la próxima porfa todas estas cosas en PRs separados

2022-01-25 04:36 UTC, manuelfrancisco commented on controllers/slides.js
> +    const data = await slidesService.create(imageUrl, text, order, organizationId)
Acá convenimos entre todos que íbamos a pasar el req.body directamente hasta el final

2022-01-25 21:38 UTC, manuelfrancisco requested changes

2022-01-25 21:38 UTC, manuelfrancisco commented on repositories/slides.js
> +  const data = await db.Slides.create({
Además de los anteriores comentarios, acá acordamos también mandar el body completo al create

2022-01-25 22:53 UTC, GimenaRivoira commented
@manuelfrancisco te adjunto como quedo 
![image](https://user-images.githubusercontent.com/73909780/151073290-4689e331-db23-46b2-8e7c-ba73dac02440.png)

2022-01-28 02:46 UTC, manuelfrancisco approved these changes

2022-01-28 02:47 UTC, merged