Ot126 47
alkemyTech/OT126-SERVER pull request #17
Opened 2022-01-23 19:03 UTC by GimenaRivoira

update for slide completed and added new function in validations for update

2022-01-25 04:40 UTC, manuelfrancisco requested changes
Mismos comentarios que para anteriores PRs

2022-01-25 04:40 UTC, manuelfrancisco commented on controllers/slides.js
> +      res.status(200).json({ msg: `Slide ${req.params.id} updated succesfully` })
Acá habría que devolver el objeto actualizado obteniéndolo desde la base, o configurando sequelize para que te devuelva ese objeto actualizado con el update

2022-01-25 22:44 UTC, GimenaRivoira commented
@manuelfrancisco Ya esta solucionado los conflictos y el tema del los errorres en el update de esta branch 
![image](https://user-images.githubusercontent.com/73909780/151072235-cc32276c-99a7-4177-bb31-eec31a453b8a.png)

2022-01-25 22:55 UTC, manuelfrancisco requested changes

2022-01-25 22:55 UTC, manuelfrancisco commented on controllers/slides.js
> +    const findOne = await slidesService.getById(req.params.id)
Esto se hace en el servicio

2022-01-28 02:50 UTC, manuelfrancisco requested changes
Cuidado al resolver conflictos

2022-01-28 02:50 UTC, manuelfrancisco commented on routes/slides.js
> +router.put('/:id', slideValidations.updateSlide, slidesController.update)
Falta el control de admin

2022-01-28 02:50 UTC, manuelfrancisco commented on services/slides.js
> +  return { data, updates }
Acá devolver sólo el registro actualizado

2022-01-29 20:17 UTC, GimenaRivoira commented on services/slides.js
> +  return { data, updates }
Devuelve un mensaje con el registro actualizado @manuelfrancisco 
![image](https://user-images.githubusercontent.com/73909780/151676242-f724750d-9620-488b-a986-4521a7cf920f.png)

2022-01-29 20:45 UTC, GimenaRivoira commented
@manuelfrancisco  EL ultimo commit me confundi de nombre y lo puse mal, el nombre seria "DELETED create function in this branch" en vez de "added create function in this branch"

2022-01-31 09:52 UTC, manuelfrancisco approved these changes

2022-02-01 16:37 UTC, merged