Ot126 61
alkemyTech/OT126-SERVER pull request #21
Opened 2022-01-24 11:04 UTC by EzeBauer

2022-01-25 04:51 UTC, manuelfrancisco requested changes

2022-01-25 04:51 UTC, manuelfrancisco commented on controllers/comments.js
> +/* const remove = async (req, res, next) => {
El remove no debería estar borrado, si no funciona hay que arreglarlo

2022-01-25 04:51 UTC, manuelfrancisco commented on services/comments.js
> +const create = async ({ user_id, novelty_id, body }) => {
Acá convenimos entre todos pasar el objeto entero

2022-01-25 17:16 UTC, EzeBauer commented on controllers/comments.js
> +/* const remove = async (req, res, next) => {
Deje comentado este metodo porque aun no fue solicitado, pero ahora lo descomento

2022-01-25 22:02 UTC, manuelfrancisco requested changes

2022-01-25 22:02 UTC, manuelfrancisco commented on migrations/20211123144230-create-activities.js
> +<<<<<<< HEAD
Acá quedó mal la resolución del conflicto

2022-01-25 22:02 UTC, manuelfrancisco commented on services/comments.js
> +  const response = await commentsRepository.create({
De nuevo acá la idea es pasar el data como viene

2022-01-25 23:11 UTC, EzeBauer commented on migrations/20211123144230-create-activities.js
> +<<<<<<< HEAD
Corregido

2022-01-25 23:11 UTC, EzeBauer commented on services/comments.js
> +  const response = await commentsRepository.create({
corregido

2022-01-26 00:50 UTC, manuelfrancisco approved these changes

2022-01-26 00:50 UTC, merged