Ot126 43
alkemyTech/OT126-SERVER pull request #23
Opened 2022-01-24 13:44 UTC by matias293

2022-01-24 13:46 UTC, matias293 commented
Added POST /contacts
Added create in controller, service and repositories
![image](https://user-images.githubusercontent.com/82419832/150794106-b4e7f085-2984-46ec-953f-382abd8b3c30.png)

2022-01-25 05:10 UTC, manuelfrancisco requested changes

2022-01-25 05:10 UTC, manuelfrancisco commented on .gitignore
> +<<<<<<< HEAD
Acá te quedó este conflicto mal resuelto

2022-01-25 05:10 UTC, manuelfrancisco commented on migrations/20211123144230-create-activities.js
> +<<<<<<< HEAD
Este otro conflicto también mal resuelto

2022-01-25 05:10 UTC, manuelfrancisco commented on routes/contacts.js
> +router.post('/', authMiddleware.isAuth, contacts, contactsController.create)
Acá se eliminó el get cuando deberían ir las dos rutas

2022-01-25 05:10 UTC, manuelfrancisco commented on controllers/contacts.js
> +    res.status(200).json({ data: contact, msg: 'El formulario se envio correctamente' })
Los mensajes en inglés

2022-01-26 00:58 UTC, manuelfrancisco approved these changes

2022-01-26 01:00 UTC, merged