Ot126 19 - Added isAdmin middleware
alkemyTech/OT126-SERVER pull request #29
Opened 2022-01-24 23:57 UTC by ecorgniali-dev

### Summary

- Added isAdmin middleware functionality

2022-01-25 06:16 UTC, manuelfrancisco requested changes

2022-01-25 06:16 UTC, manuelfrancisco commented on middlewares/auth.js
> +  const { roleId } = req.user
El user no te viene en la request, la idea es consumir el módulo que debe hacer Victor de JWT para que te devuelva el payload del token, con el userId del payload ir a buscar el usuario al servicio de users y comparar contra el roleId de ese objeto

2022-01-26 19:17 UTC, ecorgniali-dev commented on middlewares/auth.js
> +  const { roleId } = req.user
Cambios aplicados!

2022-01-28 02:56 UTC, manuelfrancisco requested changes

2022-01-28 02:56 UTC, manuelfrancisco commented on middlewares/auth.js
> +    const roleUser = await user.getRole()
Esto no existe, hay que ir a buscar el role en el repo de roles

2022-01-28 02:56 UTC, manuelfrancisco commented on middlewares/auth.js
> +    if (roleUser.name.toLowerCase() === 'admin') {
Acá te convendría hacer la condición negativa para no tener un else

2022-01-28 12:49 UTC, ecorgniali-dev commented on middlewares/auth.js
> +    const roleUser = await user.getRole()
Resuelto Manu!

2022-01-28 12:51 UTC, ecorgniali-dev commented on middlewares/auth.js
> +    if (roleUser.name.toLowerCase() === 'admin') {
Hecho!
Para no hardcodear agregué en config el nombre del rol admin.

2022-01-31 09:56 UTC, manuelfrancisco approved these changes

2022-01-31 10:21 UTC, merged