Ot126 41 - Activity update functionality
alkemyTech/OT126-SERVER pull request #35
Opened 2022-01-25 15:18 UTC by ecorgniali-dev

### Summary

Added update activities functionality for layers:

- Routes
- Controller
- Service
- Repository

Added field validation functionality update activities

2022-01-25 22:26 UTC, manuelfrancisco requested changes

2022-01-25 22:26 UTC, manuelfrancisco commented on repositories/activities.js
> +  const activity = await db.Activities.findByPk(id)
Tanto este get como la validación posterior deben ir en el service

2022-01-25 22:26 UTC, manuelfrancisco commented on repositories/activities.js
> +  if (activity == null) return false
Si no existe activity hay que hacer throw de un error con status 404. No olvides de pasar esta validación al service

2022-01-26 18:20 UTC, ecorgniali-dev commented on repositories/activities.js
> +  const activity = await db.Activities.findByPk(id)
Realizado Manu!

2022-01-26 18:20 UTC, ecorgniali-dev commented on repositories/activities.js
> +  if (activity == null) return false
Refactorización realizada!

2022-01-28 02:59 UTC, manuelfrancisco approved these changes

2022-01-28 02:59 UTC, manuelfrancisco commented on services/activities.js
> +  } else {
Te podés ahorrar el else

2022-01-28 13:01 UTC, ecorgniali-dev commented on services/activities.js
> +  } else {
Hecho.

2022-01-28 13:03 UTC, merged