Ot126 62
alkemyTech/OT126-SERVER pull request #38
Opened 2022-01-25 19:17 UTC by EzeBauer

Manu pusheo el update de commets. En la ruta deje comentado el middleware que verifica si es el usuario es dueño del comentario o si es administrador porque también depende de funcionalidad de auths middleware que tengo aun que combinar con los chicos que la desarrollaron

2022-01-25 22:50 UTC, manuelfrancisco requested changes

2022-01-25 22:50 UTC, manuelfrancisco commented on controllers/comments.js
> +      success: true,
Porfa los formatos de respuesta como los definimos

2022-01-25 22:50 UTC, manuelfrancisco commented on middlewares/isMyComents-validations.js
> +const isMyComment = async (req, res, next) => {
Porfa borrá todos los comentarios, la idea de dejar comentarios es sólo cuando realmente se necesitan. Si usás nombres descriptivos para tus variables y funciones en este caso no van a ser necesarios

2022-01-25 22:50 UTC, manuelfrancisco commented on middlewares/isMyComents-validations.js
> +    const reqId = tokenId(req); //obtiene el token decodificado y obtiene el id del usuario logueado
No sé de dónde sacaste ese método tokenId pero tengo entendido que no existe.
Además le pondría otro nombre como userId en vez de reqId

2022-01-25 22:50 UTC, manuelfrancisco commented on middlewares/isMyComents-validations.js
> +const usersService = require("../services/users");
Hay un archivo de middelware creado que se llama comments, y todo esto debería ir en un método ahí que se llame isOwnComment, podés borrar todo el código comentado y poner el tuyo.

2022-01-26 00:37 UTC, EzeBauer commented on controllers/comments.js
> +      success: true,
resuelto

2022-01-26 00:37 UTC, EzeBauer commented on middlewares/isMyComents-validations.js
> +const isMyComment = async (req, res, next) => {
Comentarios borrados

2022-01-26 00:38 UTC, EzeBauer commented on middlewares/isMyComents-validations.js
> +const usersService = require("../services/users");
Codigo pasado a middelware comments-validations

2022-01-26 00:39 UTC, EzeBauer commented
El middleware no lo pude resolver aun manuel, despues lo voy a ver con los chicos para que me den una mano, pero el empoint para modificar un comentario esta funcionando bien

2022-01-28 03:04 UTC, manuelfrancisco requested changes

2022-01-28 03:04 UTC, manuelfrancisco commented on controllers/comments.js
> +      success: true,
Esto no está resuelto, el success está de más y el Comment se debe llamar data

2022-01-28 03:04 UTC, manuelfrancisco commented on middlewares/isMyComents-validations.js
> +const isMyComment = async (req, res, next) => {
No veo que se hayan borrado los comentarios

2022-01-28 03:04 UTC, manuelfrancisco commented on middlewares/isMyComents-validations.js
> +const usersService = require("../services/users");
Porfa volvé a leer el comentario original. Es en la carpeta middlewares, el archivo contacts, el método se llama isOwnComment

2022-01-28 03:04 UTC, manuelfrancisco commented on services/comments.js
> +  console.log(comments);
Eliminar el console.log

2022-01-30 22:57 UTC, EzeBauer commented
Por fin validador isOwnComent funcionando correctamente

2022-01-31 10:06 UTC, manuelfrancisco requested changes

2022-01-31 10:06 UTC, manuelfrancisco commented on models/comments.js
> +        onDelete: 'cascade',
las cascadas no tienen que ir, es una mala práctica

2022-01-31 10:06 UTC, manuelfrancisco commented on routes/slides.js
> +/* router.post('/create', slideValidations, slidesController.create) */
Por qué está comentado este post?

2022-01-31 11:57 UTC, manuelfrancisco requested changes

2022-01-31 11:57 UTC, manuelfrancisco commented on middlewares/comments-validations.js
> +    if (roleUser.name === 'Admin') return next()
Hay una propiedad del config que podés consumir para no harcodear el nombre del role que se llama adminRoleName

2022-01-31 15:19 UTC, EzeBauer commented on models/comments.js
> +        onDelete: 'cascade',
Ya las quite

2022-01-31 15:19 UTC, EzeBauer commented on middlewares/comments-validations.js
> +    if (roleUser.name === 'Admin') return next()
yo lo llame de config

2022-01-31 15:20 UTC, EzeBauer commented on routes/slides.js
> +/* router.post('/create', slideValidations, slidesController.create) */
Lo comente porque me crasheaba y no me levantaba el proyecto, pero ya lo subi sin comentar

2022-02-01 08:57 UTC, manuelfrancisco approved these changes

2022-02-01 08:57 UTC, merged