add middleware isOwnUser
alkemyTech/OT126-SERVER pull request #39
Opened 2022-01-25 20:52 UTC by valentarayre

# Summary
Function impremented verifies whether it is the owner or a member manager

2022-01-25 22:51 UTC, manuelfrancisco requested changes

2022-01-25 22:51 UTC, manuelfrancisco commented on middlewares/auth.js
> +    if(user.roleID === 2) return next()
Porfa no hardcodeemos, buscá el rol yendo al repo de roles, hay un método para buscar por nombre

2022-01-25 23:11 UTC, valentarayre commented on middlewares/auth.js
> +    if(user.roleID === 2) return next()
En el repositorio no existe algo para los roles. Ya lo creo y lo uso

2022-01-26 01:04 UTC, manuelfrancisco approved these changes

2022-01-26 01:06 UTC, merged