Ot126 15
alkemyTech/OT126-SERVER pull request #43
Opened 2022-01-26 13:21 UTC by matias293

### Summary

- Added route GET organization/public
- Added getById in controller, service and repository

2022-01-28 03:08 UTC, manuelfrancisco requested changes

2022-01-28 03:08 UTC, manuelfrancisco commented on controllers/organizations.js
> +    if (!data) {
Esta validación se hace en el service

2022-01-29 13:20 UTC, OmiMauro commented on repositories/organizations.js
> +    attributes: ['name', 'image', 'phone', 'address']
Creo que faltaría agrear los atributos email y welcomeText, ya que es necesario para enviar el email de bienvenida

2022-01-31 10:09 UTC, manuelfrancisco approved these changes

2022-01-31 10:13 UTC, merged