Ot126 26 - User Update feature
alkemyTech/OT126-SERVER pull request #47
Opened 2022-01-27 18:10 UTC by Vungyr

Added User update feature

- Add route update
- Add controller update
- Add service update
- Add repository update
- Add validations

2022-01-28 03:28 UTC, manuelfrancisco requested changes

2022-01-28 03:28 UTC, manuelfrancisco commented on middlewares/auth.js
> +  getTokenPayload
El método getTokenPayload no debe exportarse

2022-01-28 03:28 UTC, manuelfrancisco commented on repositories/users.js
> +const getById = async (id, exclude) => {
El parámetro exclude no debe estar.
Conceptualmente cualquiera que consuma el repository desconoce los campos de la base, los métodos del repository tienen que ser una caja negra de la cual se consume o se accede a los datos pero que no expone nada de su comportamiento.

2022-01-28 03:28 UTC, manuelfrancisco commented on services/users.js
> +// check the current password whit the DB password and return a newPassword
Por favor sin comentarios, el código debe ser lo suficientemente claro en nombre de variables, funciones, etc para que los programadores se den cuenta de su comportamiento sin tener comentarios. Sólo se agregan comentarios en casos estrictamente necesarios.

2022-01-28 03:28 UTC, manuelfrancisco commented on services/users.js
> +const checkPasswords = async (body, payload) => {
Me parece que esta función tiene muchas responsabilidades. Busca los datos del usuario, hace validaciones, devuelve un hash de contraseña... yo separaría las distintas responsabilidades en más funciones para darle claridad y atomicidad.

2022-01-29 18:35 UTC, Vungyr commented on middlewares/auth.js
> +  getTokenPayload
se lo usa para matchear las contraseñas.

2022-01-29 18:35 UTC, Vungyr commented on middlewares/auth.js
> +  getTokenPayload
se lo usa para matchear las contraseñas.

2022-01-31 11:37 UTC, manuelfrancisco requested changes
Si tenés problemas para plantear la lógica o las responsabilidades avisame y lo vemos a la tarede

2022-01-31 11:37 UTC, manuelfrancisco commented on services/users.js
> +  const user = await usersRepository.getById(payload.userId)
Yo diría que esto hay que recibirlo por parámetro, sino estás en la misma que antes estás dándole más responsabilidad de la que le corresponde a este método

2022-01-31 11:37 UTC, manuelfrancisco commented on repositories/users.js
> +const getById = async (id, exclude) => {
Seguís recibiendo un parámetro que no estás usando

2022-01-31 11:37 UTC, manuelfrancisco commented on services/users.js
> +  const passwordsMatch = bcrypt.compareSync(body.currentPassword, user.password)
Esta comparación siempre te va a dar un resultado negativo porque la password del usuario en base ya está hasheada, deberías recibir también la password ya hasheada para comparar

2022-02-01 00:23 UTC, Vungyr commented on services/users.js
> +  const passwordsMatch = bcrypt.compareSync(body.currentPassword, user.password)
compareSync permite recibir un pass sin hashear para comparar con un hash

2022-02-01 08:59 UTC, manuelfrancisco approved these changes

2022-02-01 09:55 UTC, merged