Ot126 39
alkemyTech/OT126-SERVER pull request #48
Opened 2022-01-27 18:49 UTC by GimenaRivoira

2022-01-28 03:31 UTC, manuelfrancisco requested changes

2022-01-28 03:31 UTC, manuelfrancisco commented on services/auth.js
> +  const usuario = await usersRepository.findByEmail(body.email)
No hace falta obtener el usuario nuevamente, el create te devuelve el registro. De hecho le cambiaría el nombre a la variable register para darle claridad.

2022-01-28 03:31 UTC, manuelfrancisco commented on services/auth.js
> +  const token = getToken(usuario)
No veo la declaración de esta función getToken. Deberías consumirla del authModule que tenés comentado.

2022-01-29 20:59 UTC, GimenaRivoira commented on services/auth.js
> +  const token = getToken(usuario)
La funcion que se utiliza esta aca. unas lineas mas abajo se encuentra
![image](https://user-images.githubusercontent.com/73909780/151677362-d78e8f53-0727-4f24-8bfa-404ec1206e74.png)

2022-01-31 12:04 UTC, manuelfrancisco requested changes

2022-01-31 12:04 UTC, manuelfrancisco commented on services/auth.js
> +    roleId: body.roleId = 1
Primero que nada hicimos la convención entre todos de pasar el body tal cual viene. Ahora, el role no está bueno harcodearlo, sería mejor ir a buscarlo al repository de roles por nombre, podés hacer una clave en el config para el role Standard asi como está el Admin. Yo te recomendaría que hagas más o menos lo siguiente

```
const standardRole = await rolesRepository.getByName(standardRoleName)
const newUser = {
    ...body,
    roleId: standardRole.id,
    password: bcrypt.hashSync(body.password, 12)
}
const createdUser = await usersRepository.create(newUser)
```
Como verás también le cambié el nombre a la constante register que tenés más abajo, es importante ser descriptivo con los nombres de las variables/constantes, funciones, etc.

2022-02-04 15:17 UTC, closed without merging