Ot126 63
alkemyTech/OT126-SERVER pull request #50
Opened 2022-01-27 21:47 UTC by EzeBauer

Listado de commentarios por id de novedad

2022-01-28 03:36 UTC, manuelfrancisco requested changes

2022-01-28 03:36 UTC, manuelfrancisco commented on controllers/news.js
> +const getCommentsByNewId = async (req, res, next) => {
getCommentsByNoveltyId

2022-01-28 03:36 UTC, manuelfrancisco commented on repositories/news.js
> +const getCommentsByNewId = async (id) => {
getCommentsByNoveltyId

2022-01-28 03:36 UTC, manuelfrancisco commented on services/news.js
> +const getCommentsByNewId = async (id) => {
getCommentsByNoveltyId

2022-01-28 03:36 UTC, manuelfrancisco commented on services/news.js
> +  if (novelty <= 0) {
Esta condición debería ser `if (!novelty)`

2022-01-28 11:03 UTC, manuelfrancisco approved these changes

2022-01-29 00:24 UTC, EzeBauer commented on repositories/news.js
> +const getCommentsByNewId = async (id) => {
Cambiado

2022-01-29 00:24 UTC, EzeBauer commented on services/news.js
> +  if (novelty <= 0) {
hecho

2022-01-29 00:25 UTC, EzeBauer commented on services/news.js
> +const getCommentsByNewId = async (id) => {
Cambiado

2022-01-29 00:28 UTC, merged