Refactor and Fix errors to run, of first sprint
alkemyTech/OT126-SERVER pull request #51
Opened 2022-01-28 01:01 UTC by gonzalo-m-ortiz

## Summary

- Eslint fix applied to all files
- Minor errors, caused by code integration, fixed. Now app run correctly
- Express error handler fixed, now returning JSON

2022-01-28 01:04 UTC, gonzalo-m-ortiz commented on middlewares/auth.js
> +    const token = await getTokenPayload(req)
@OmiMauro, acá creo que no era necesario el await

2022-01-28 03:42 UTC, manuelfrancisco requested changes

2022-01-28 03:42 UTC, manuelfrancisco commented on middlewares/auth.js
> +    const token = await getTokenPayload(req)
Correcto, hasta le sacaste el async del método.

2022-01-28 03:42 UTC, manuelfrancisco commented on middlewares/testimonials-validations.js
> +// validators
Porfa sin comentarios inútiles

2022-01-28 03:42 UTC, manuelfrancisco commented on modules/auth.js
> +// Create token
Porfa borrar los comentarios

2022-02-01 09:00 UTC, manuelfrancisco approved these changes

2022-02-01 10:14 UTC, merged