Ot126 22 - Send Email Signup
alkemyTech/OT126-SERVER pull request #55
Opened 2022-01-29 14:38 UTC by OmiMauro

## Summary
- Send email when user was register succesfully in the server

2022-01-31 23:00 UTC, gonzalo-m-ortiz commented on services/auth.js
> +    await send(headersEmail)
@OmiMauro  te dejo mi feedback.
Deberías implementar un catch acá.
Como está ahora si el mail falla, la petición a register devuelve un 500. Aunque el usuario si se haya creado.
```js
await send(headersEmail).catch(error => {
  /* TODO Log to devs why mail was not sent
     console.log(error.message) */
})
```

2022-01-31 23:01 UTC, gonzalo-m-ortiz commented on services/auth.js
> +      text: `${organization.welcomeText}`
Esto de acá va a ser ignorado por el módulo de emails. Creo que lo mencioné en la "documentación" de la función `send`

2022-01-31 23:02 UTC, gonzalo-m-ortiz commented on services/auth.js
> +      subject: `Welcome to ${organization.name}`,
Acá acordate que esto le llega al usuario final. En el caso de este proyecto, debería estar en español supongo

2022-02-01 09:20 UTC, manuelfrancisco requested changes

2022-02-01 09:20 UTC, manuelfrancisco commented on services/auth.js
> +    await send(headersEmail)
Me parece correcta la aclaración, aunque lo implementaría con try catch en vez de un catch de una promesa

2022-02-01 23:05 UTC, manuelfrancisco approved these changes

2022-02-01 23:38 UTC, merged