OT126-48
alkemyTech/OT126-SERVER pull request #57
Opened 2022-01-29 20:12 UTC by GimenaRivoira

Todos los slides agregados al endpoint publico de organizacion

2022-01-31 22:36 UTC, gonzalo-m-ortiz reviewed
@GimenaRivoira Creo que la tarea no era crear otro endpoint para el listado de slides, sino al getById que ya está hecho (está en dev, pero no en esta rama), agregarle el listado de slides en la respuesta.

2022-02-01 09:22 UTC, manuelfrancisco requested changes

2022-02-01 09:22 UTC, manuelfrancisco commented on controllers/organizations.js
> +const getAll = async (req, res, next) => {
La idea no era crear un endpoint nuevo sino usar el que ya está creado, es una funcionalidad que tenía Mati podes preguntarle a él dónde está ese endpoint

2022-02-03 18:25 UTC, GimenaRivoira commented on controllers/organizations.js
> +const getAll = async (req, res, next) => {
Listo, agregado.

2022-02-03 20:58 UTC, manuelfrancisco approved these changes

2022-02-03 21:23 UTC, merged