Update 20201109013159-create-demo-user.js
alkemyTech/OT126-SERVER pull request #58
Opened 2022-01-29 23:04 UTC by Vungyr

Create users seeders

2022-01-31 22:27 UTC, gonzalo-m-ortiz reviewed
@Vungyr, podés hacer el commit para añadir la info al README.md en este PR

2022-02-01 09:24 UTC, manuelfrancisco requested changes

2022-02-01 09:24 UTC, manuelfrancisco commented on seeders/20201109013159-create-demo-user.js
> +  up: async (queryInterface, Sequelize) =>
Muy bien pero ahora faltaría cambiar el README.md

2022-02-01 13:42 UTC, Vungyr commented on seeders/20201109013159-create-demo-user.js
> +  up: async (queryInterface, Sequelize) =>
README.md modificado

2022-02-01 23:07 UTC, manuelfrancisco approved these changes

2022-02-01 23:07 UTC, merged