Ot126-28 Create auth/me
alkemyTech/OT126-SERVER pull request #63
Opened 2022-01-31 13:14 UTC by valentarayre

# Summary
- Creation of the new path /auth/me
  - add new function in controllers, routes, services in auth.js
  
# Evidence 
![image](https://user-images.githubusercontent.com/87746742/151799574-5674a93f-f12a-4f97-b159-e5d1f17127dd.png)
![image](https://user-images.githubusercontent.com/87746742/151799713-710035c0-b1af-44da-89a8-544700e91ca1.png)

2022-01-31 22:03 UTC, gonzalo-m-ortiz reviewed
Valen, te doy mi feedback
Para mí los middlewares de auth tendrían que asignar un objeto `user: { id: tokenPayload.userId }` al objeto `req`. Entonces vos tendrías que hacer un getById normal sin usar el token. 
Si te parece bien, podés plantear esto al equipo para que hagan las modificaciones en middlewares/auth. Creo que esto solucionaría otros problemas con otros endpoints

2022-01-31 22:12 UTC, valentarayre commented
> 

Eso iba hacer el proximo daily, iba a cometar que estaria bueno que el middlawares, devuelvan el payload en el req.body. Gracias por el comentario

2022-02-01 09:29 UTC, manuelfrancisco requested changes

2022-02-01 09:29 UTC, manuelfrancisco commented on controllers/auth.js
> +const getByToken = async (req, res, next) => {
Como la ruta tiene el middleware de isAuth aplicado estarías repitiendo código al volver a obtener tanto el token como el usuario de la bd. Podrías editar ese middelware para guardarte en la req el authUser y tu método de controller no llamaría a ningún service, sino que escribiría la respuesta y nada más (envuelto en try catch)

2022-02-01 23:09 UTC, manuelfrancisco approved these changes

2022-02-01 23:09 UTC, merged