Ot126 50
alkemyTech/OT126-SERVER pull request #73
Opened 2022-02-01 23:03 UTC by EzeBauer

Este es el correcto, el anterior apunta a main

2022-02-01 23:18 UTC, manuelfrancisco requested changes

2022-02-01 23:18 UTC, manuelfrancisco commented on modules/sendEmailContact.js
> +    .then((data) => data)
este then sobra si estás trabajando con async await, además no hace absolutamente nada

2022-02-01 23:18 UTC, manuelfrancisco commented on modules/sendEmailContact.js
> +  return await ejs.renderFile(path.join(process.cwd(), 'templates', 'emailContact.ejs'), data)
la ruta guardala en una constante

2022-02-01 23:18 UTC, manuelfrancisco commented on services/contacts.js
> +      const headersEmail = {
el armado del objeto y el envío del email lo haría en un método aparte que no se exponga

2022-02-02 00:49 UTC, EzeBauer commented on modules/sendEmailContact.js
> +    .then((data) => data)
then eliminado

2022-02-02 00:50 UTC, EzeBauer commented on modules/sendEmailContact.js
> +  return await ejs.renderFile(path.join(process.cwd(), 'templates', 'emailContact.ejs'), data)
constante creada

2022-02-02 00:50 UTC, EzeBauer commented on services/contacts.js
> +      const headersEmail = {
metodo aparte creado

2022-02-02 01:55 UTC, manuelfrancisco requested changes

2022-02-02 01:55 UTC, manuelfrancisco commented on modules/sendEmailContact.js
> +  const ruteTemplate = await ejs.renderFile(path.join(process.cwd(), 'templates', 'emailContact.ejs'), data)
Esa no es la ruta...

2022-02-03 21:11 UTC, manuelfrancisco requested changes

2022-02-03 21:11 UTC, manuelfrancisco commented on modules/objectTemplateEmail.js
> +    const error = new Error('Email sent failed')
Acá no tiraría un error, lo loggearía de alguna manera (por ahora en la consola, luego vemos cómo) y lo dejaría seguir. Vos pensá que se puede crear el contacto pero si al enviar el email se produce un error se terminaría devolviendo que hubo un error cuando el contacto se envió bien, y eso no sería correcto.

2022-02-03 21:49 UTC, manuelfrancisco approved these changes

2022-02-05 04:44 UTC, merged